import '../models/event_model.dart';
import '../models/user_model.dart';
import '../models/badge_model.dart';

/// Servicio de datos mock para desarrollo y testing
class MockDataService {
  // Datos de usuario simulado
  static UserModel get mockVolunteer => UserModel(
    id: '1',
    email: 'violeta@example.com',
    name: 'Violeta García',
    userType: UserType.volunteer,
    photoUrl: null,
    phone: '+34 600 123 456',
    bio: 'Estudiante apasionada por el medio ambiente',
    createdAt: DateTime.now().subtract(const Duration(days: 90)),
    skills: ['Comunicación', 'Organización', 'Fotografía'],
    interests: ['Medio Ambiente', 'Educación', 'Animales'],
    totalHours: 45,
    eventsCompleted: 8,
    badges: ['first_event', 'environmental_hero', 'social_butterfly'],
  );

  // Eventos mock
  static List<EventModel> get mockEvents => [
    EventModel(
      id: '1',
      title: 'Limpieza de Playa Barceloneta',
      description: 'Únete a nosotros para limpiar la playa y proteger la vida marina. Proporcionaremos todos los materiales necesarios.',
      organizationId: 'org1',
      organizationName: 'Green Earth Foundation',
      date: DateTime.now().add(const Duration(days: 5)),
      location: 'Playa Barceloneta, Barcelona',
      latitude: 41.3809,
      longitude: 2.1909,
      maxVolunteers: 30,
      currentVolunteers: 18,
      requiredSkills: [],
      category: 'Medio Ambiente',
      imageUrl: null,
      estimatedHours: 4,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      registeredVolunteers: [],
    ),
    EventModel(
      id: '2',
      title: 'Taller de Reciclaje Creativo',
      description: 'Aprende a crear arte y objetos útiles a partir de materiales reciclados. Perfecto para todas las edades.',
      organizationId: 'org2',
      organizationName: 'EcoArte Colectivo',
      date: DateTime.now().add(const Duration(days: 3)),
      location: 'Centro Cultural, Madrid',
      latitude: 40.4168,
      longitude: -3.7038,
      maxVolunteers: 20,
      currentVolunteers: 15,
      requiredSkills: ['Creatividad', 'Manualidades'],
      category: 'Educación',
      imageUrl: null,
      estimatedHours: 3,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      registeredVolunteers: [],
    ),
    EventModel(
      id: '3',
      title: 'Reforestación Sierra de Guadarrama',
      description: 'Ayúdanos a plantar 500 árboles nativos en la Sierra de Guadarrama. Incluye transporte y comida.',
      organizationId: 'org1',
      organizationName: 'Green Earth Foundation',
      date: DateTime.now().add(const Duration(days: 12)),
      location: 'Sierra de Guadarrama, Madrid',
      latitude: 40.7789,
      longitude: -4.0897,
      maxVolunteers: 50,
      currentVolunteers: 32,
      requiredSkills: [],
      category: 'Medio Ambiente',
      imageUrl: null,
      estimatedHours: 6,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      registeredVolunteers: [],
    ),
    EventModel(
      id: '4',
      title: 'Apoyo Comedor Social',
      description: 'Colabora en la preparación y distribución de comidas para personas en situación de vulnerabilidad.',
      organizationId: 'org3',
      organizationName: 'Solidaridad en Acción',
      date: DateTime.now().add(const Duration(days: 2)),
      location: 'Comedor Social, Valencia',
      latitude: 39.4699,
      longitude: -0.3763,
      maxVolunteers: 15,
      currentVolunteers: 15,
      requiredSkills: [],
      category: 'Social',
      imageUrl: null,
      estimatedHours: 5,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      registeredVolunteers: [],
    ),
    EventModel(
      id: '5',
      title: 'Clases de Español para Refugiados',
      description: 'Enseña español básico a personas refugiadas. No se requiere experiencia previa en enseñanza.',
      organizationId: 'org4',
      organizationName: 'Puentes Culturales',
      date: DateTime.now().add(const Duration(days: 7)),
      location: 'Centro de Acogida, Sevilla',
      latitude: 37.3886,
      longitude: -5.9823,
      maxVolunteers: 10,
      currentVolunteers: 6,
      requiredSkills: ['Paciencia', 'Comunicación'],
      category: 'Educación',
      imageUrl: null,
      estimatedHours: 2,
      isActive: true,
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      registeredVolunteers: [],
    ),
  ];

  // Badges mock
  static List<BadgeModel> get mockBadges => [
    BadgeModel(
      id: 'first_event',
      name: 'Primer Paso',
      description: 'Completaste tu primer evento de voluntariado',
      iconName: 'star',
      category: BadgeCategory.milestone,
      requiredPoints: 1,
      isEarned: true,
      earnedDate: DateTime.now().subtract(const Duration(days: 80)),
    ),
    BadgeModel(
      id: 'environmental_hero',
      name: 'Héroe Ambiental',
      description: 'Participaste en 5 eventos ambientales',
      iconName: 'eco',
      category: BadgeCategory.environmental,
      requiredPoints: 5,
      isEarned: true,
      earnedDate: DateTime.now().subtract(const Duration(days: 30)),
    ),
    BadgeModel(
      id: 'social_butterfly',
      name: 'Mariposa Social',
      description: 'Participaste en 3 eventos sociales',
      iconName: 'people',
      category: BadgeCategory.social,
      requiredPoints: 3,
      isEarned: true,
      earnedDate: DateTime.now().subtract(const Duration(days: 15)),
    ),
    BadgeModel(
      id: 'time_master',
      name: 'Maestro del Tiempo',
      description: 'Acumulaste 50 horas de voluntariado',
      iconName: 'schedule',
      category: BadgeCategory.milestone,
      requiredPoints: 50,
      isEarned: false,
      earnedDate: null,
    ),
    BadgeModel(
      id: 'educator',
      name: 'Educador',
      description: 'Participaste en 5 eventos educativos',
      iconName: 'school',
      category: BadgeCategory.educational,
      requiredPoints: 5,
      isEarned: false,
      earnedDate: null,
    ),
  ];
}
